window.RESOURCE_DATA = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    type: "ai",
    category: "对话写作",
    description: "通用 AI 助手，适合写作、头脑风暴、翻译、代码解释和日常问答。",
    bestFor: "个人效率、新媒体选题、学习辅助",
    price: "免费可用 / 付费升级",
    platforms: ["Web", "iOS", "Android", "桌面端"],
    access: "需确认网络环境",
    url: "https://chatgpt.com/",
    domain: "chatgpt.com",
    tags: ["starter", "creator", "writing", "coding"],
    featured: true
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    type: "ai",
    category: "对话写作",
    description: "中文体验友好的 AI 助手，适合问答、写作、代码和长文本处理。",
    bestFor: "中文写作、学习问答、代码辅助",
    price: "免费可用",
    platforms: ["Web", "App"],
    access: "国内访问友好",
    url: "https://chat.deepseek.com/",
    domain: "deepseek.com",
    tags: ["starter", "domestic", "writing", "coding"],
    featured: true
  },
  {
    id: "kimi",
    name: "Kimi",
    type: "ai",
    category: "对话写作",
    description: "适合中文长文档阅读、资料总结、写作润色和信息整理。",
    bestFor: "长文档、论文资料、公众号写作",
    price: "免费可用 / 付费升级",
    platforms: ["Web", "App"],
    access: "国内访问友好",
    url: "https://kimi.moonshot.cn/",
    domain: "kimi.moonshot.cn",
    tags: ["starter", "domestic", "writing", "office"],
    featured: true
  },
  {
    id: "tongyi",
    name: "通义千问",
    type: "ai",
    category: "对话写作",
    description: "阿里云推出的通用大模型助手，覆盖写作、办公、学习和多模态能力。",
    bestFor: "中文办公、学习、文案生成",
    price: "免费可用 / 付费升级",
    platforms: ["Web", "App"],
    access: "国内访问友好",
    url: "https://tongyi.aliyun.com/",
    domain: "tongyi.aliyun.com",
    tags: ["starter", "domestic", "writing"],
    featured: false
  },
  {
    id: "doubao",
    name: "豆包",
    type: "ai",
    category: "对话写作",
    description: "面向大众用户的 AI 助手，适合日常问答、写作、图片理解和办公场景。",
    bestFor: "日常问答、内容生成、移动端使用",
    price: "免费可用",
    platforms: ["Web", "App", "桌面端"],
    access: "国内访问友好",
    url: "https://www.doubao.com/",
    domain: "doubao.com",
    tags: ["starter", "domestic", "writing"],
    featured: false
  },
  {
    id: "claude",
    name: "Claude",
    type: "ai",
    category: "对话写作",
    description: "擅长长文本阅读、复杂写作、代码理解和结构化分析的 AI 助手。",
    bestFor: "长文本、英文写作、代码审阅",
    price: "免费可用 / 付费升级",
    platforms: ["Web", "App"],
    access: "需确认网络环境",
    url: "https://claude.ai/",
    domain: "claude.ai",
    tags: ["writing", "coding", "office"],
    featured: false
  },
  {
    id: "perplexity",
    name: "Perplexity",
    type: "ai",
    category: "搜索研究",
    description: "带引用来源的 AI 搜索工具，适合快速调研、资料核查和竞品信息整理。",
    bestFor: "资料检索、选题研究、英文信息源",
    price: "免费可用 / 付费升级",
    platforms: ["Web", "App"],
    access: "需确认网络环境",
    url: "https://www.perplexity.ai/",
    domain: "perplexity.ai",
    tags: ["starter", "research", "office"],
    featured: true
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    type: "ai",
    category: "办公协作",
    description: "集成在 Notion 中的写作、总结、翻译和知识库问答能力。",
    bestFor: "团队文档、知识库、项目记录",
    price: "付费功能",
    platforms: ["Web", "桌面端", "App"],
    access: "需确认网络环境",
    url: "https://www.notion.so/product/ai",
    domain: "notion.so",
    tags: ["office", "writing"],
    featured: false
  },
  {
    id: "canva",
    name: "Canva",
    type: "ai",
    category: "图片设计",
    description: "在线设计平台，适合海报、封面、PPT、社媒图和轻量 AI 设计。",
    bestFor: "公众号封面、小红书图、PPT 视觉",
    price: "免费可用 / 付费升级",
    platforms: ["Web", "App"],
    access: "国内访问需确认",
    url: "https://www.canva.com/",
    domain: "canva.com",
    tags: ["starter", "creator", "design"],
    featured: true
  },
  {
    id: "remove-bg",
    name: "remove.bg",
    type: "ai",
    category: "图片设计",
    description: "一键去除图片背景，适合商品图、头像和封面素材处理。",
    bestFor: "抠图、封面素材、商品图",
    price: "免费可用 / 付费高清",
    platforms: ["Web"],
    access: "需确认网络环境",
    url: "https://www.remove.bg/",
    domain: "remove.bg",
    tags: ["starter", "creator", "design"],
    featured: false
  },
  {
    id: "midjourney",
    name: "Midjourney",
    type: "ai",
    category: "图片设计",
    description: "高质量 AI 绘图工具，适合概念图、视觉风格探索和创意素材生成。",
    bestFor: "商业视觉、创意探索、概念设计",
    price: "付费订阅",
    platforms: ["Web", "Discord"],
    access: "需确认网络环境",
    url: "https://www.midjourney.com/",
    domain: "midjourney.com",
    tags: ["creator", "design"],
    featured: false
  },
  {
    id: "jimeng",
    name: "即梦 AI",
    type: "ai",
    category: "图片设计",
    description: "面向中文用户的 AI 图片和视频创作工具，适合短视频素材和视觉创意。",
    bestFor: "图片生成、视频创意、中文提示词",
    price: "免费可用 / 付费升级",
    platforms: ["Web", "App"],
    access: "国内访问友好",
    url: "https://jimeng.jianying.com/",
    domain: "jimeng.jianying.com",
    tags: ["creator", "domestic", "design", "video"],
    featured: true
  },
  {
    id: "jianying",
    name: "剪映",
    type: "ai",
    category: "视频音频",
    description: "视频剪辑工具，适合短视频剪辑、字幕识别、模板制作和内容分发。",
    bestFor: "短视频、口播、字幕、模板",
    price: "免费可用 / 付费素材",
    platforms: ["Windows", "macOS", "iOS", "Android", "Web"],
    access: "国内访问友好",
    url: "https://www.capcut.cn/",
    domain: "capcut.cn",
    tags: ["starter", "creator", "domestic", "video"],
    featured: true
  },
  {
    id: "runway",
    name: "Runway",
    type: "ai",
    category: "视频音频",
    description: "AI 视频生成和编辑平台，适合创意短片、镜头生成和视觉实验。",
    bestFor: "AI 视频、创意广告、动态素材",
    price: "免费试用 / 付费升级",
    platforms: ["Web", "App"],
    access: "需确认网络环境",
    url: "https://runwayml.com/",
    domain: "runwayml.com",
    tags: ["creator", "video"],
    featured: false
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    type: "ai",
    category: "视频音频",
    description: "AI 语音生成与配音工具，适合旁白、播客和多语言音频制作。",
    bestFor: "AI 配音、英文旁白、音频内容",
    price: "免费可用 / 付费升级",
    platforms: ["Web"],
    access: "需确认网络环境",
    url: "https://elevenlabs.io/",
    domain: "elevenlabs.io",
    tags: ["creator", "audio"],
    featured: false
  },
  {
    id: "cursor",
    name: "Cursor",
    type: "ai",
    category: "编程开发",
    description: "AI 代码编辑器，适合项目理解、代码生成、重构和问答式开发。",
    bestFor: "开发者、独立产品、自动化脚本",
    price: "免费可用 / 付费升级",
    platforms: ["Windows", "macOS", "Linux"],
    access: "需确认网络环境",
    url: "https://cursor.com/",
    domain: "cursor.com",
    tags: ["coding", "developer"],
    featured: true
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    type: "ai",
    category: "编程开发",
    description: "集成在编辑器中的 AI 编程助手，适合补全、解释、测试和代码生成。",
    bestFor: "专业开发、IDE 编码、测试生成",
    price: "付费订阅 / 部分人群免费",
    platforms: ["VS Code", "JetBrains", "Visual Studio"],
    access: "需确认网络环境",
    url: "https://github.com/features/copilot",
    domain: "github.com",
    tags: ["coding", "developer"],
    featured: false
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    type: "computer",
    category: "开发工具",
    description: "轻量代码编辑器，插件生态完整，适合前端、脚本、数据和文档编辑。",
    bestFor: "开发学习、脚本编辑、Markdown",
    price: "免费",
    platforms: ["Windows", "macOS", "Linux"],
    access: "国内访问友好",
    url: "https://code.visualstudio.com/",
    domain: "code.visualstudio.com",
    tags: ["starter", "developer", "free", "domestic"],
    featured: true
  },
  {
    id: "powertoys",
    name: "Microsoft PowerToys",
    type: "computer",
    category: "系统效率",
    description: "Windows 官方效率工具箱，包含窗口布局、批量重命名、取色器和快速启动。",
    bestFor: "Windows 装机、效率增强",
    price: "免费",
    platforms: ["Windows"],
    access: "国内访问友好",
    url: "https://learn.microsoft.com/windows/powertoys/",
    domain: "learn.microsoft.com",
    tags: ["starter", "office", "free", "domestic"],
    featured: true
  },
  {
    id: "everything",
    name: "Everything",
    type: "computer",
    category: "系统效率",
    description: "Windows 文件名搜索神器，索引快，适合快速找到本地文件。",
    bestFor: "文件搜索、办公资料定位",
    price: "免费",
    platforms: ["Windows"],
    access: "国内访问友好",
    url: "https://www.voidtools.com/",
    domain: "voidtools.com",
    tags: ["starter", "office", "free", "domestic"],
    featured: true
  },
  {
    id: "utools",
    name: "uTools",
    type: "computer",
    category: "系统效率",
    description: "插件化效率启动器，适合搜索、翻译、剪贴板、快捷工作流和小工具集合。",
    bestFor: "快捷启动、插件效率、办公工具",
    price: "免费可用 / 付费升级",
    platforms: ["Windows", "macOS", "Linux"],
    access: "国内访问友好",
    url: "https://www.u-tools.cn/",
    domain: "u-tools.cn",
    tags: ["starter", "office", "domestic"],
    featured: false
  },
  {
    id: "snipaste",
    name: "Snipaste",
    type: "computer",
    category: "截图录屏",
    description: "截图、贴图和标注工具，轻量稳定，适合办公、教程和产品反馈。",
    bestFor: "截图标注、贴图参考、教程制作",
    price: "免费可用 / 专业版",
    platforms: ["Windows", "macOS"],
    access: "国内访问友好",
    url: "https://www.snipaste.com/",
    domain: "snipaste.com",
    tags: ["starter", "office", "free", "domestic"],
    featured: true
  },
  {
    id: "obs",
    name: "OBS Studio",
    type: "computer",
    category: "截图录屏",
    description: "开源录屏和直播软件，适合课程录制、屏幕演示和直播推流。",
    bestFor: "录屏、直播、课程制作",
    price: "免费开源",
    platforms: ["Windows", "macOS", "Linux"],
    access: "国内访问友好",
    url: "https://obsproject.com/",
    domain: "obsproject.com",
    tags: ["creator", "office", "free", "video"],
    featured: false
  },
  {
    id: "sharex",
    name: "ShareX",
    type: "computer",
    category: "截图录屏",
    description: "开源截图与录屏工具，支持自动上传、OCR、标注和多种工作流。",
    bestFor: "高级截图、自动化、技术文档",
    price: "免费开源",
    platforms: ["Windows"],
    access: "国内访问友好",
    url: "https://getsharex.com/",
    domain: "getsharex.com",
    tags: ["office", "free", "developer", "domestic"],
    featured: false
  },
  {
    id: "chrome",
    name: "Google Chrome",
    type: "computer",
    category: "浏览下载",
    description: "主流浏览器，插件生态丰富，适合作为跨平台工作浏览器。",
    bestFor: "网页应用、插件生态、跨端同步",
    price: "免费",
    platforms: ["Windows", "macOS", "Linux", "iOS", "Android"],
    access: "需确认网络环境",
    url: "https://www.google.com/chrome/",
    domain: "google.com",
    tags: ["starter", "free"],
    featured: false
  },
  {
    id: "edge",
    name: "Microsoft Edge",
    type: "computer",
    category: "浏览下载",
    description: "Windows 默认浏览器，兼容 Chromium 插件，适合办公和网页阅读。",
    bestFor: "Windows 办公、PDF 阅读、网页应用",
    price: "免费",
    platforms: ["Windows", "macOS", "Linux", "iOS", "Android"],
    access: "国内访问友好",
    url: "https://www.microsoft.com/edge",
    domain: "microsoft.com",
    tags: ["starter", "office", "free", "domestic"],
    featured: false
  },
  {
    id: "motrix",
    name: "Motrix",
    type: "computer",
    category: "浏览下载",
    description: "跨平台下载工具，支持 HTTP、FTP、BT、磁力链接等常见下载任务。",
    bestFor: "文件下载、跨平台下载管理",
    price: "免费开源",
    platforms: ["Windows", "macOS", "Linux"],
    access: "国内访问友好",
    url: "https://motrix.app/",
    domain: "motrix.app",
    tags: ["starter", "free", "domestic"],
    featured: false
  },
  {
    id: "7zip",
    name: "7-Zip",
    type: "computer",
    category: "压缩安全",
    description: "经典开源压缩工具，支持 7z、zip、rar 等常见格式解压。",
    bestFor: "压缩解压、装机基础工具",
    price: "免费开源",
    platforms: ["Windows"],
    access: "国内访问友好",
    url: "https://www.7-zip.org/",
    domain: "7-zip.org",
    tags: ["starter", "free", "domestic"],
    featured: true
  },
  {
    id: "bandizip",
    name: "Bandizip",
    type: "computer",
    category: "压缩安全",
    description: "界面友好的压缩解压工具，适合日常文件打包和常见格式处理。",
    bestFor: "日常压缩、批量文件处理",
    price: "免费可用 / 专业版",
    platforms: ["Windows", "macOS"],
    access: "国内访问友好",
    url: "https://www.bandisoft.com/bandizip/",
    domain: "bandisoft.com",
    tags: ["starter", "domestic"],
    featured: false
  },
  {
    id: "pdfgear",
    name: "PDFgear",
    type: "computer",
    category: "文档 PDF",
    description: "PDF 阅读、编辑、转换和注释工具，适合日常办公文档处理。",
    bestFor: "PDF 编辑、格式转换、文档批注",
    price: "免费可用",
    platforms: ["Windows", "macOS", "iOS"],
    access: "国内访问友好",
    url: "https://www.pdfgear.com/",
    domain: "pdfgear.com",
    tags: ["starter", "office", "free", "domestic"],
    featured: true
  },
  {
    id: "wps",
    name: "WPS Office",
    type: "computer",
    category: "文档 PDF",
    description: "国产办公套件，覆盖文字、表格、演示、PDF 和模板资源。",
    bestFor: "日常办公、学生作业、文档协作",
    price: "免费可用 / 会员功能",
    platforms: ["Windows", "macOS", "Linux", "iOS", "Android"],
    access: "国内访问友好",
    url: "https://www.wps.cn/",
    domain: "wps.cn",
    tags: ["starter", "office", "domestic"],
    featured: false
  },
  {
    id: "localsend",
    name: "LocalSend",
    type: "computer",
    category: "文件传输",
    description: "局域网文件传输工具，跨平台、开源，适合手机和电脑互传文件。",
    bestFor: "跨设备传文件、局域网协作",
    price: "免费开源",
    platforms: ["Windows", "macOS", "Linux", "iOS", "Android"],
    access: "国内访问友好",
    url: "https://localsend.org/",
    domain: "localsend.org",
    tags: ["starter", "office", "free", "domestic"],
    featured: false
  },
  {
    id: "git",
    name: "Git",
    type: "computer",
    category: "开发工具",
    description: "版本控制工具，是代码管理、协作开发和部署流程的基础组件。",
    bestFor: "代码管理、协作开发、部署",
    price: "免费开源",
    platforms: ["Windows", "macOS", "Linux"],
    access: "国内访问友好",
    url: "https://git-scm.com/",
    domain: "git-scm.com",
    tags: ["developer", "free", "domestic"],
    featured: false
  },
  {
    id: "nodejs",
    name: "Node.js",
    type: "computer",
    category: "开发工具",
    description: "JavaScript 运行时，适合前端工程、脚本、自动化和服务端开发。",
    bestFor: "前端开发、工具链、自动化脚本",
    price: "免费开源",
    platforms: ["Windows", "macOS", "Linux"],
    access: "国内访问友好",
    url: "https://nodejs.org/",
    domain: "nodejs.org",
    tags: ["developer", "free", "domestic"],
    featured: false
  }
];
